#+TITLE: jrrom's Literate Configurations

* Reasoning
Hello, I'm [[www.github.com/jrrom][jrrom]]. This is my literate configuration for my daily use. I use [[https://www.gnu.org/software/stow/][GNU Stow]] for keeping track of my dotfiles. I used to use [[https://github.com/nix-community/home-manager][home-manager]] but I dislike the Nix interface and prefer doing it "directly." If you see anything you like then feel free to copy!

I am trying to move away from NixOS, and currently in the process of doing so. This is very much still a work in progress.

* To Be Completed
** Pre-Migration
- [ ] Clean up Firefox Mozilla bookmarks, manage Mozilla account
- [ ] Save music, documents and files.
- [ ] Clean up emails and email accounts, etc...
- [ ] Clean up computer and work on moving certain things online <-- Centralise and standardise
- [ ] Clean up online drive
- [ ] Finish website
- [ ] Complete parkour game
- [ ] Migrate to Gentoo and remove Nix
- [ ] Document entire process on website
- [ ] Delete the root directory in dotfiles
- [ ] Use Systemd boot
** Post Migration
- [ ] Add font and theme to personal Gentoo overlay along with other effects
- [ ] Writeup of all dependencies and packages (least no. of packages for most gain)
- [ ] No greetd, make a user Systemd service that runs sway
- [ ] Use Systemd brightness service
- [ ] Fix sway and waybar
